

daily_metadata_to_publish_retro <- function(data_file, data_in_file, remake_file, gd_config){

  data_in = readRDS(data_in_file)

  col_names = colnames(data_in)

  rm(data_in)

  description = c('Model time step',
                  'Date of model output',
                  'Surface water inflow to the lake',
                  'Direct precipitation on the lake surface',
                  'Evaporation from the lake surface',
                  'Groundwater inflow to the lake',
                  'Groundwater outflow from the lake',
                  'Surface water outflow from the lake',
                  'Snowmelt on top of lake ice directly into the lake',
                  'Stream baseflow contribution to the lake',
                  'Lake surface area',
                  'Lake shoreline perimeter',
                  'Lake maximum depth',
                  'Lake elevation above sea level',
                  'Lake volume',
                  'Snow depth on top of lake ice',
                  'Atmospheric CO2 concentration',
                  'Total phytoplankton biomass',
                  'Phosphorus mass in the lake epilimnion',
                  'Phosphorus mass in the lake hypolimnion',
                  'Dissolved inorganic carbon mass in the lake epilimnion',
                  'Dissolved inorganic carbon mass in the lake hypolimnion',
                  'Recalcitrant dissolved organic carbon mass in the lake epilimnion',
                  'Recalcitrant dissolved organic carbon mass in the lake hypolimnion',
                  'Labile dissolved organic carbon mass in the lake epilimnion',
                  'Labile dissolved organic carbon mass in the lake hypolimnion',
                  'Terrestrial particulate organic carbon mass in the lake epilimnion',
                  'Terrestrial particulate organic carbon mass in the lake hypolimnion',
                  'Mass of carbon emitted as CO2 from the lake surface',
                  'Mass of terrestrial particulate organic carbon sedimented out of the lake water column',
                  'Mass of phyotplankton carbon sedimented out of the lake water column',
                  'Mixed layer depth',
                  'Light attenuation coefficient in the lake epilimnion',
                  'Epilimnetic gross primary production',
                  'Lake epilimnion volume',
                  'Lake hypolimnion volume',
                  'Gas exchange coefficient for CO2',
                  'Lake epilimnion water temperature',
                  'Lake hypolimnion water temperature',
                  'Mass of terrestrial particulate organic carbon buried in the lake sediment',
                  'Mass of phytoplankton carbon buried in the lake sediment',
                  'Mass of dissolved organic carbon loaded to the lake',
                  'Mass of dissolved organic carbon exported from the lake through fluvial routes (i.e. groundwater, surface water)',
                  'Mass of dissolved organic carbon respired within the lake',
                  'Mass of dissolved organic carbon respired within the lake excluding respiration of phytoplankton exude',
                  'Turnover rate of lake dissolved organic carbon based on the relative size of the recalcitrant and labile DOC pools and water temperature in the epilimnion',
                  'Turnover rate of lake dissolved organic carbon based on the relative size of the recalcitrant and labile DOC pools and water temperature in the hypolimnion',
                  'Epilimnetic pH',
                  'Fraction of dissolved inorganic carbon pool that is in the form of CO2',
                  'Permanent_ID from the medium resolution USGS National Hydrography Dataset',
                  'Weather data file used to drive the integrated model')

  units = c('Integer',
            'Date',
            'm^3 day^-1',
            'm^3 day^-1',
            'm^3 day^-1',
            'm^3 day^-1',
            'm^3 day^-1',
            'm^3 day^-1',
            'm^3 day^-1',
            'm^3 day^-1',
            'm^2',
            'm',
            'm',
            'm',
            'm^3',
            'm',
            'ppm',
            'mol C',
            'mol P',
            'mol P',
            'mol C',
            'mol C',
            'mol C',
            'mol C',
            'mol C',
            'mol C',
            'mol C',
            'mol C',
            'mol C day^-1',
            'mol C day^-1',
            'mol C day^-1',
            'm',
            'm-1',
            'mol C day^-1',
            'm^3',
            'm^3',
            'm day^-1',
            'degrees Celsius',
            'degrees Celsius',
            'mol C day^-1',
            'mol C day^-1',
            'mol C day^-1',
            'mol C day^-1',
            'mol C day^-1',
            'mol C day^-1',
            'day^-1',
            'day^-1',
            ' ',
            'fraction',
            'ID',
            'String')

  metadata_out = tibble(column_name = col_names,
                    column_description = description,
                    column_unit = units)

  saveRDS(metadata_out, data_file)
}



daily_metadata_to_publish_scenarios <- function(data_file, data_in_file, remake_file, gd_config){

  data_in = readRDS(data_in_file)

  col_names = colnames(data_in)

  rm(data_in)

  description = c('Model time step',
                  'Date of model output in reference to retrospective model run',
                  'Surface water inflow to the lake',
                  'Direct precipitation on the lake surface',
                  'Evaporation from the lake surface',
                  'Groundwater inflow to the lake',
                  'Groundwater outflow from the lake',
                  'Surface water outflow from the lake',
                  'Snowmelt on top of lake ice directly into the lake',
                  'Stream baseflow contribution to the lake',
                  'Lake surface area',
                  'Lake shoreline perimeter',
                  'Lake maximum depth',
                  'Lake elevation above sea level',
                  'Lake volume',
                  'Snow depth on top of lake ice',
                  'Atmospheric CO2 concentration',
                  'Total phytoplankton biomass',
                  'Phosphorus mass in the lake epilimnion',
                  'Phosphorus mass in the lake hypolimnion',
                  'Dissolved inorganic carbon mass in the lake epilimnion',
                  'Dissolved inorganic carbon mass in the lake hypolimnion',
                  'Recalcitrant dissolved organic carbon mass in the lake epilimnion',
                  'Recalcitrant dissolved organic carbon mass in the lake hypolimnion',
                  'Labile dissolved organic carbon mass in the lake epilimnion',
                  'Labile dissolved organic carbon mass in the lake hypolimnion',
                  'Terrestrial particulate organic carbon mass in the lake epilimnion',
                  'Terrestrial particulate organic carbon mass in the lake hypolimnion',
                  'Mass of carbon emitted as CO2 from the lake surface',
                  'Mass of terrestrial particulate organic carbon sedimented out of the lake water column',
                  'Mass of phyotplankton carbon sedimented out of the lake water column',
                  'Mixed layer depth',
                  'Light attenuation coefficient in the lake epilimnion',
                  'Epilimnetic gross primary production',
                  'Lake epilimnion volume',
                  'Lake hypolimnion volume',
                  'Gas exchange coefficient for CO2',
                  'Lake epilimnion water temperature',
                  'Lake hypolimnion water temperature',
                  'Mass of terrestrial particulate organic carbon buried in the lake sediment',
                  'Mass of phytoplankton carbon buried in the lake sediment',
                  'Mass of dissolved organic carbon loaded to the lake',
                  'Mass of dissolved organic carbon exported from the lake through fluvial routes (i.e. groundwater, surface water)',
                  'Mass of dissolved organic carbon respired within the lake',
                  'Mass of dissolved organic carbon respired within the lake excluding respiration of phytoplankton exude',
                  'Turnover rate of lake dissolved organic carbon based on the relative size of the recalcitrant and labile DOC pools and water temperature in the epilimnion',
                  'Turnover rate of lake dissolved organic carbon based on the relative size of the recalcitrant and labile DOC pools and water temperature in the hypolimnion',
                  'Epilimnetic pH',
                  'Fraction of dissolved inorganic carbon pool that is in the form of CO2',
                  'Permanent_ID from the medium resolution USGS National Hydrography Dataset',
                  'Weather data file used to drive the integrated model')

  units = c('Integer',
            'Date',
            'm^3 day^-1',
            'm^3 day^-1',
            'm^3 day^-1',
            'm^3 day^-1',
            'm^3 day^-1',
            'm^3 day^-1',
            'm^3 day^-1',
            'm^3 day^-1',
            'm^2',
            'm',
            'm',
            'm',
            'm^3',
            'm',
            'ppm',
            'mol C',
            'mol P',
            'mol P',
            'mol C',
            'mol C',
            'mol C',
            'mol C',
            'mol C',
            'mol C',
            'mol C',
            'mol C',
            'mol C day^-1',
            'mol C day^-1',
            'mol C day^-1',
            'm',
            'm-1',
            'mol C day^-1',
            'm^3',
            'm^3',
            'm day^-1',
            'degrees Celsius',
            'degrees Celsius',
            'mol C day^-1',
            'mol C day^-1',
            'mol C day^-1',
            'mol C day^-1',
            'mol C day^-1',
            'mol C day^-1',
            'day^-1',
            'day^-1',
            ' ',
            'fraction',
            'ID',
            'String')

  metadata_out = tibble(column_name = col_names,
                        column_description = description,
                        column_unit = units)

  saveRDS(metadata_out, data_file)
}



