
data_to_publish <- function(ind_file, data_in_file, remake_file, gd_config){


  data_in = readRDS(data_in_file)

  col_names = colnames(data_in)

  description = c('Permanent_ID from the medium resolution USGS National Hydrography Dataset',
                  'Average surface water inflow to the lake',
                  'Average direct precipitation on the lake surface',
                  'Average evaporation from the lake surface',
                  'Average groundwater inflow to the lake',
                  'Average groundwater outflow from the lake',
                  'Average surface water outflow from the lake',
                  'GET RID OF THIS',
                  'GET RID OF THIS',
                  'Average snowmelt on top of lake ice directly into the lake',
                  'GET RID OF THIS',
                  'GET RID OF THIS',
                  'Average stream baseflow contribution to the lake',
                  'Average lake surface area',
                  'GET RID OF THIS',
                  'Average lake shoreline perimeter',
                  'Average lake maximum depth',
                  'Average lake elevation above sea level',
                  'Average lake volume',
                  'Average snow depth on top of lake ice',
                  'Average atmospheric CO2 concentration',
                  'Average total phytoplankton biomass',
                  'Average phosphorus mass in the lake epilimnion',
                  'Average phosphorus mass in the lake hypolimnion',
                  'Average dissolved inorganic carbon mass in the lake epilimnion',
                  'Average dissolved inorganic carbon mass in the lake hypolimnion',
                  'Average recalcitrant dissolved organic carbon mass in the lake epilimnion',
                  'Average recalcitrant dissolved organic carbon mass in the lake hypolimnion',
                  'Average labile dissolved organic carbon mass in the lake epilimnion',
                  'Average labile dissolved organic carbon mass in the lake hypolimnion',
                  'Average terrestrial particulate organic carbon mass in the lake epilimnion',
                  'Average terrestrial particulate organic carbon mass in the lake hypolimnion',
                  'Average mass of carbon emitted as CO2 from the lake surface',
                  'Average mass of terrestrial particulate organic carbon sedimented out of the lake water column',
                  'Average mass of phyotplankton carbon sedimented out of the lake water column',
                  'Average mixed layer depth',
                  'Average light attenuation coefficient in the lake epilimnion',
                  'Average epilimnetic gross primary production',
                  'Average lake epilimnion volume',
                  'Average lake hypolimnion volume',
                  'Average gas exchange coefficient for CO2',
                  'Average lake epilimnion water temperature',
                  'Average lake hypolimnion water temperature',
                  'Average mass of terrestrial particulate organic carbon buried in the lake sediment',
                  'Average mass of phytoplankton carbon buried in the lake sediment',
                  'Average mass of dissolved organic carbon loaded to the lake',
                  'Average mass of dissolved organic carbon exported from the lake through fluvial routes (i.e. groundwater, surface water)',
                  'Average mass of dissolved organic carbon respired within the lake',
                  'Average mass of dissolved organic carbon respired within the lake excluding respiration of phytoplankton exude',
                  'Average turnover rate of lake dissolved organic carbon based on the relative size of the recalcitrant and labile DOC pools and water temperature in the epilimnion',
                  'Average turnover rate of lake dissolved organic carbon based on the relative size of the recalcitrant and labile DOC pools and water temperature in the hypolimnion',
                  'Average epilimnetic pH',
                  'Average fraction of dissolved inorganic carbon pool that is in the form of CO2',
                  'GET RID OF THIS',
                  'Total number of days of ice cover over simulation period',
                  'GET RID OF THIS',
                  'GET RID OF THIS',
                  'GET RID OF THIS',
                  'GET RID OF THIS',
                  'Lake catchment area',
                  'Average watershed area to lake area ratio',
                  'GET RID OF THIS',
                  'Number of raster cells in lake watershed with "Water" landcover class from the National Land Cover Databse 2011',
                  'Number of raster cells in lake watershed with "Perennial Ice Snow" landcover class from the National Land Cover Databse 2011',
                  'Number of raster cells in lake watershed with "Developed, Open Space" landcover class from the National Land Cover Databse 2011',
                  'Number of raster cells in lake watershed with "Developed, Low Intensity" landcover class from the National Land Cover Databse 2011',
                  'Number of raster cells in lake watershed with "Developed, Medium Intensity" landcover class from the National Land Cover Databse 2011',
                  'Number of raster cells in lake watershed with "Developed, High Intensity" landcover class from the National Land Cover Databse 2011',
                  'Number of raster cells in lake watershed with "Bare Rock/Sand/Clay" landcover class from the National Land Cover Databse 2011',
                  'Number of raster cells in lake watershed with "Deciduous Forest" landcover class from the National Land Cover Databse 2011',
                  'Number of raster cells in lake watershed with "Evergreen Forest" landcover class from the National Land Cover Databse 2011',
                  'Number of raster cells in lake watershed with "Mixed Forest" landcover class from the National Land Cover Databse 2011',
                  'Number of raster cells in lake watershed with "Shrub/Scrub" landcover class from the National Land Cover Databse 2011',
                  'Number of raster cells in lake watershed with "Grasslands/Herbaceous" landcover class from the National Land Cover Databse 2011',
                  'Number of raster cells in lake watershed with "Pasture/Hay" landcover class from the National Land Cover Databse 2011',
                  'Number of raster cells in lake watershed with "Cultivated Crops" landcover class from the National Land Cover Databse 2011',
                  'Number of raster cells in lake watershed with "Woody Wetlands" landcover class from the National Land Cover Databse 2011',
                  'Number of raster cells in lake watershed with "Emergent Herbaceous Wetlands" landcover class from the National Land Cover Databse 2011',
                  'Total number of raster cells in lake watershed with a landcover class from the National Land Cover Databse 2011',
                  'Fraction of lake watershed area that is classified as wetland based on National Land Cover Database 2011',
                  'Average lake epilimnetic alkalinity',
                  'Average lake hydrologic residence time',
                  'Average lake hydrologic residence time based on fluvial exports (excluding evaporative exports)',
                  'Average fraction of loaded dissolved organic carbon that is removed within the lake',
                  'Average mass of dissolved inorganic carbon loaded to the lake',
                  'Average mass of carbon respired in the lake sediments',
                  'Average amount of water loaded to lake',
                  'Average amount of water lost to fluvial exports from the lake',
                  'Average fraction of mass of dissolved inorganic carbon loaded to the lake compared to the mass of dissolved inorganic carbon produced within the lake from respiration of organic carbon both dissolved and particulate',
                  'Average fraction of hydrologic export from the lake as evaporation',
                  'Average total (terrestrial POC and phytoplankton carbon) mass of carbon buried in lake sediments',
                  'Average partial pressure of CO2 in the lake epilimnion',
                  'Average volume-weighted lake dissolved organic carbon concentration (weighted by relative epi- hypo-limnion volumes)',
                  'Average mass of phosphorus loaded to the lake',
                  'GET RID OF THIS',
                  'Simulation period',
                  'GET RID OF THIS',
                  'Global Climate Model used to drive weather data')

  units = c('ID',
            'm^3 day^-1',
            'm^3 day^-1',
            'm^3 day^-1',
            'm^3 day^-1',
            'm^3 day^-1',
            'm^3 day^-1',
            'm^3 day^-1',
            'm^3 day^-1',
            'm^3 day^-1',
            'm^3 day^-1',
            'm^3 day^-1',
            'm^3 day^-1',
            'm^2',
            'm',
            'm',
            'm',
            'm',
            'm^3',
            'm',
            'ppm',
            'mol C',
            'mol P',
            'mol P',
            'mol C',
            'mol C',
            'mol C',
            'mol C',
            'mol C',
            'mol C',
            'mol C',
            'mol C',
            'mol C day^-1',
            'mol C day^-1',
            'mol C day^-1',
            'm',
            'm-1',
            'mol C day^-1',
            'm^3',
            'm^3',
            'm day^-1',
            'degrees Celsius',
            'degrees Celsius',
            'mol C day^-1',
            'mol C day^-1',
            'mol C day^-1',
            'mol C day^-1',
            'mol C day^-1',
            'mol C day^-1',
            'day^-1',
            'day^-1',
            ' ',
            'fraction',
            'days',
            'days',
            'ID',
            'ID',
            'ID',
            'ID',
            'm^2',
            'fraction',
            'number of raster cells',
            'number of raster cells',
            'number of raster cells',
            'number of raster cells',
            'number of raster cells',
            'number of raster cells',
            'number of raster cells',
            'number of raster cells',
            'number of raster cells',
            'number of raster cells',
            'number of raster cells',
            'number of raster cells',
            'number of raster cells',
            'number of raster cells',
            'number of raster cells',
            'number of raster cells',
            'number of raster cells',
            'number of raster cells',
            'fraction',
            'uEq L^-1',
            'days',
            'days',
            'fraction',
            'mol C day^-1',
            'mol C day^-1',
            'm^3 day^-1',
            'm^3 day^-1',
            'faction',
            'fraction',
            'mol C day^-1',
            'ppm',
            'mg C L^-1',
            'mol P day^-1',
            'category',
            'categorical time period',
            'categorical season',
            'global climate model')

  metadata_out = tibble(column_name = col_names,
                    column_description = description,
                    column_unit = units) %>%
    dplyr::slice(-grep('GET RID OF THIS', column_description))

  data_out = select(data_in, -grep('GET RID OF THIS', description))

  if(!all(colnames(data_out) %in% metadata_out$column_name)){
    stop('Not all data columns have associated metadata')
  }

  data_file = as_data_file(ind_file)
  saveRDS(data_out, data_file)
  gd_put(remote_ind = ind_file, local_source = data_file, config_file = gd_config)
}


metadata_to_publish <- function(ind_file, data_in_file, remake_file, gd_config){

  data_in = readRDS(data_in_file)

  col_names = colnames(data_in)

  description = c('Permanent_ID from the medium resolution USGS National Hydrography Dataset',
                  'Average surface water inflow to the lake',
                  'Average direct precipitation on the lake surface',
                  'Average evaporation from the lake surface',
                  'Average groundwater inflow to the lake',
                  'Average groundwater outflow from the lake',
                  'Average surface water outflow from the lake',
                  'GET RID OF THIS',
                  'GET RID OF THIS',
                  'Average snowmelt on top of lake ice directly into the lake',
                  'GET RID OF THIS',
                  'GET RID OF THIS',
                  'Average stream baseflow contribution to the lake',
                  'Average lake surface area',
                  'GET RID OF THIS',
                  'Average lake shoreline perimeter',
                  'Average lake maximum depth',
                  'Average lake elevation above sea level',
                  'Average lake volume',
                  'Average snow depth on top of lake ice',
                  'Average atmospheric CO2 concentration',
                  'Average total phytoplankton biomass',
                  'Average phosphorus mass in the lake epilimnion',
                  'Average phosphorus mass in the lake hypolimnion',
                  'Average dissolved inorganic carbon mass in the lake epilimnion',
                  'Average dissolved inorganic carbon mass in the lake hypolimnion',
                  'Average recalcitrant dissolved organic carbon mass in the lake epilimnion',
                  'Average recalcitrant dissolved organic carbon mass in the lake hypolimnion',
                  'Average labile dissolved organic carbon mass in the lake epilimnion',
                  'Average labile dissolved organic carbon mass in the lake hypolimnion',
                  'Average terrestrial particulate organic carbon mass in the lake epilimnion',
                  'Average terrestrial particulate organic carbon mass in the lake hypolimnion',
                  'Average mass of carbon emitted as CO2 from the lake surface',
                  'Average mass of terrestrial particulate organic carbon sedimented out of the lake water column',
                  'Average mass of phyotplankton carbon sedimented out of the lake water column',
                  'Average mixed layer depth',
                  'Average light attenuation coefficient in the lake epilimnion',
                  'Average epilimnetic gross primary production',
                  'Average lake epilimnion volume',
                  'Average lake hypolimnion volume',
                  'Average gas exchange coefficient for CO2',
                  'Average lake epilimnion water temperature',
                  'Average lake hypolimnion water temperature',
                  'Average mass of terrestrial particulate organic carbon buried in the lake sediment',
                  'Average mass of phytoplankton carbon buried in the lake sediment',
                  'Average mass of dissolved organic carbon loaded to the lake',
                  'Average mass of dissolved organic carbon exported from the lake through fluvial routes (i.e. groundwater, surface water)',
                  'Average mass of dissolved organic carbon respired within the lake',
                  'Average mass of dissolved organic carbon respired within the lake excluding respiration of phytoplankton exude',
                  'Average turnover rate of lake dissolved organic carbon based on the relative size of the recalcitrant and labile DOC pools and water temperature in the epilimnion',
                  'Average turnover rate of lake dissolved organic carbon based on the relative size of the recalcitrant and labile DOC pools and water temperature in the hypolimnion',
                  'Average epilimnetic pH',
                  'Average fraction of dissolved inorganic carbon pool that is in the form of CO2',
                  'GET RID OF THIS',
                  'Total number of days of ice cover over simulation period',
                  'GET RID OF THIS',
                  'GET RID OF THIS',
                  'GET RID OF THIS',
                  'GET RID OF THIS',
                  'Lake catchment area',
                  'Average watershed area to lake area ratio',
                  'GET RID OF THIS',
                  'Number of raster cells in lake watershed with "Water" landcover class from the National Land Cover Databse 2011',
                  'Number of raster cells in lake watershed with "Perennial Ice Snow" landcover class from the National Land Cover Databse 2011',
                  'Number of raster cells in lake watershed with "Developed, Open Space" landcover class from the National Land Cover Databse 2011',
                  'Number of raster cells in lake watershed with "Developed, Low Intensity" landcover class from the National Land Cover Databse 2011',
                  'Number of raster cells in lake watershed with "Developed, Medium Intensity" landcover class from the National Land Cover Databse 2011',
                  'Number of raster cells in lake watershed with "Developed, High Intensity" landcover class from the National Land Cover Databse 2011',
                  'Number of raster cells in lake watershed with "Bare Rock/Sand/Clay" landcover class from the National Land Cover Databse 2011',
                  'Number of raster cells in lake watershed with "Deciduous Forest" landcover class from the National Land Cover Databse 2011',
                  'Number of raster cells in lake watershed with "Evergreen Forest" landcover class from the National Land Cover Databse 2011',
                  'Number of raster cells in lake watershed with "Mixed Forest" landcover class from the National Land Cover Databse 2011',
                  'Number of raster cells in lake watershed with "Shrub/Scrub" landcover class from the National Land Cover Databse 2011',
                  'Number of raster cells in lake watershed with "Grasslands/Herbaceous" landcover class from the National Land Cover Databse 2011',
                  'Number of raster cells in lake watershed with "Pasture/Hay" landcover class from the National Land Cover Databse 2011',
                  'Number of raster cells in lake watershed with "Cultivated Crops" landcover class from the National Land Cover Databse 2011',
                  'Number of raster cells in lake watershed with "Woody Wetlands" landcover class from the National Land Cover Databse 2011',
                  'Number of raster cells in lake watershed with "Emergent Herbaceous Wetlands" landcover class from the National Land Cover Databse 2011',
                  'Total number of raster cells in lake watershed with a landcover class from the National Land Cover Databse 2011',
                  'Fraction of lake watershed area that is classified as wetland based on National Land Cover Database 2011',
                  'Average lake epilimnetic alkalinity',
                  'Average lake hydrologic residence time',
                  'Average lake hydrologic residence time based on fluvial exports (excluding evaporative exports)',
                  'Average fraction of loaded dissolved organic carbon that is removed within the lake',
                  'Average mass of dissolved inorganic carbon loaded to the lake',
                  'Average mass of carbon respired in the lake sediments',
                  'Average amount of water loaded to lake',
                  'Average amount of water lost to fluvial exports from the lake',
                  'Average fraction of mass of dissolved inorganic carbon loaded to the lake compared to the mass of dissolved inorganic carbon produced within the lake from respiration of organic carbon both dissolved and particulate',
                  'Average fraction of hydrologic export from the lake as evaporation',
                  'Average total (terrestrial POC and phytoplankton carbon) mass of carbon buried in lake sediments',
                  'Average partial pressure of CO2 in the lake epilimnion',
                  'Average volume-weighted lake dissolved organic carbon concentration (weighted by relative epi- hypo-limnion volumes)',
                  'Average mass of phosphorus loaded to the lake',
                  'GET RID OF THIS',
                  'Simulation period',
                  'GET RID OF THIS',
                  'Global Climate Model used to drive weather data')

  units = c('ID',
            'm^3 day^-1',
            'm^3 day^-1',
            'm^3 day^-1',
            'm^3 day^-1',
            'm^3 day^-1',
            'm^3 day^-1',
            'm^3 day^-1',
            'm^3 day^-1',
            'm^3 day^-1',
            'm^3 day^-1',
            'm^3 day^-1',
            'm^3 day^-1',
            'm^2',
            'm',
            'm',
            'm',
            'm',
            'm^3',
            'm',
            'ppm',
            'mol C',
            'mol P',
            'mol P',
            'mol C',
            'mol C',
            'mol C',
            'mol C',
            'mol C',
            'mol C',
            'mol C',
            'mol C',
            'mol C day^-1',
            'mol C day^-1',
            'mol C day^-1',
            'm',
            'm-1',
            'mol C day^-1',
            'm^3',
            'm^3',
            'm day^-1',
            'degrees Celsius',
            'degrees Celsius',
            'mol C day^-1',
            'mol C day^-1',
            'mol C day^-1',
            'mol C day^-1',
            'mol C day^-1',
            'mol C day^-1',
            'day^-1',
            'day^-1',
            ' ',
            'fraction',
            'days',
            'days',
            'ID',
            'ID',
            'ID',
            'ID',
            'm^2',
            'fraction',
            'number of raster cells',
            'number of raster cells',
            'number of raster cells',
            'number of raster cells',
            'number of raster cells',
            'number of raster cells',
            'number of raster cells',
            'number of raster cells',
            'number of raster cells',
            'number of raster cells',
            'number of raster cells',
            'number of raster cells',
            'number of raster cells',
            'number of raster cells',
            'number of raster cells',
            'number of raster cells',
            'number of raster cells',
            'number of raster cells',
            'fraction',
            'uEq L^-1',
            'days',
            'days',
            'fraction',
            'mol C day^-1',
            'mol C day^-1',
            'm^3 day^-1',
            'm^3 day^-1',
            'faction',
            'fraction',
            'mol C day^-1',
            'ppm',
            'mg C L^-1',
            'mol P day^-1',
            'category',
            'categorical time period',
            'categorical season',
            'global climate model')

  metadata_out = tibble(column_name = col_names,
                    column_description = description,
                    column_unit = units) %>%
    dplyr::slice(-grep('GET RID OF THIS', column_description))

  data_out = select(data_in, -grep('GET RID OF THIS', description))

  if(!all(colnames(data_out) %in% metadata_out$column_name)){
    stop('Not all data columns have associated metadata')
  }

  data_file = as_data_file(ind_file)
  saveRDS(metadata_out, data_file)
  gd_put(remote_ind = ind_file, local_source = data_file, config_file = gd_config)
}






