
# view, dimensions
bbox: [-91, 40, -84, 47]
projection: "+proj=lcc +lat_1=34.83333333333334 +lat_2=32.5 +lat_0=31.83333333333333 +lon_0=-81 +x_0=609600 +y_0=0 +ellps=GRS80 +units=m +no_defs "
height: 1000
width: 1024

focus_geoms:
  - # U.S. states
    database: state

secondary_geoms:
  - # Canada
    database: "mapdata::worldHires"
    regions: "Canada"
  - # USA
    database: "mapdata::worldHires"
    regions: "USA"
  - # states
    database: state

cities:
  dot: # parameters for general coloring of the
    bg: "gray40"
    col: "gray40"
    pch: 5
    cex: 1
  text:
    col: "gray40"
    font: 1
    cex: 1.1
    angle: 330 # angle in radians for position of label relative to dot. pos is computed from angle: 225-315=1, 315-45=4, 45-135=3, 135-225=2
    dist: 0.007 # relative (fraction of window width) distance from dot to label
  pop_min: 500000 # minimum population size of cities to be chosen by default; `custom` will make additions or modifications and `exclude` will make subtractions
  custom: # cities to add or modify relative to the maps::us.cities dataset. added cities can use lat/long from us.cities if they are present in us.cities, even if they don't meet the pop_min criterion
    #-
    #  name: "Richmond VA"
    #  text_angle: 170
    -
      name: "Raleigh NC"
      text_angle: 170
    -
      name: "Charlotte NC"
      text_angle: 170
    -
      name: "Columbia SC"
      text_angle: 170
    #-
    #  name: "Savannah GA"
    #  text_angle: 170
    #-
    #  name: "Jacksonville FL"
    #-
    #  name: "Virginia Beach VA"
    #  dot_cex: 0.8
    #  text_cex: 0.8
    #-
    #  name: "Nags Head NC"
    #  lat: 35.9425
    #  long: -75.6228
    #  dot_cex: 0.8
    #  text_cex: 0.8
    -
      name: "New Bern NC"
      news: "CBS"
      dot_cex: 0.8
      text_cex: 0.8
      lat: 35.107686
      long: -77.051366
    -
      name: "Wilmington NC"
      news: "CBS"
      dot_cex: 0.8
      text_cex: 0.8
    -
      name: "Myrtle Beach SC"
      news: "CBS"
      lat: 33.6917
      long: -78.8875
      dot_cex: 0.8
      text_cex: 0.8
    #-
    #  name: "Charleston SC"
    #  news: "google/crisismap"
    #  dot_cex: 0.8
    #  text_cex: 0.8
    # UPCOMING ALONG STORM TRACK:
    #-
    #  name: "Knoxville TN"
    #-
    #  name: "Columbus OH"
    #-
    #  name: "Pittsburgh PA"
    #-
    #  name: "New York NY"
    #-
    #  name: "Boston MA"

  exclude:
    - "Knoxville TN"
    - "Richmond VA"
    - "Memphis TN"
    - "Oklahoma City OK"
    - "Fort Worth TX"
    - "Dallas TX"
    - "Chicago IL"
    - "Baltimore MD"
    - "WASHINGTON DC"
    - "Indianapolis IN"
    - "Nashville TN"
    - "Jacksonville FL"


# Only waterbodies greater than this area will be fetched.
fetch_waterbody_areasqkm: 1000
